import { createFileRoute } from "@tanstack/react-router";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

// GET /api/public/vector-tile?z=&x=&y=&layer_id=
// Returns an MVT tile (application/x-protobuf) generated by PostGIS.
export const Route = createFileRoute("/api/public/vector-tile")({
  server: {
    handlers: {
      GET: async ({ request }) => {
        const url = new URL(request.url);
        const z = Number(url.searchParams.get("z"));
        const x = Number(url.searchParams.get("x"));
        const y = Number(url.searchParams.get("y"));
        const layerId = url.searchParams.get("layer_id");
        if (
          !layerId ||
          !Number.isFinite(z) ||
          !Number.isFinite(x) ||
          !Number.isFinite(y) ||
          z < 0 ||
          z > 22
        ) {
          return new Response("bad request", { status: 400 });
        }

        const { data, error } = await supabaseAdmin.rpc("get_vector_tile", {
          _layer_id: layerId,
          _z: z,
          _x: x,
          _y: y,
        });
        if (error) {
          return new Response(error.message, { status: 500 });
        }
        if (!data || data === "") {
          // Empty tile (nothing in this area). Return 204 to let Leaflet skip.
          return new Response(null, { status: 204 });
        }
        // Base64 -> bytes
        const b64 = String(data);
        const bin = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
        return new Response(bin, {
          status: 200,
          headers: {
            "Content-Type": "application/x-protobuf",
            "Cache-Control": "public, max-age=3600",
            "Access-Control-Allow-Origin": "*",
          },
        });
      },
    },
  },
});
