/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LicencasRouteImport } from './routes/licencas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencasRoute = LicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/licencas': typeof LicencasRoute
  '/mapa': typeof MapaRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/licencas': typeof LicencasRoute
  '/mapa': typeof MapaRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/licencas': typeof LicencasRoute
  '/mapa': typeof MapaRoute
  '/monitoramento': typeof MonitoramentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/clientes'
    | '/licencas'
    | '/mapa'
    | '/monitoramento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alertas' | '/clientes' | '/licencas' | '/mapa' | '/monitoramento'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/clientes'
    | '/licencas'
    | '/mapa'
    | '/monitoramento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ClientesRoute: typeof ClientesRoute
  LicencasRoute: typeof LicencasRoute
  MapaRoute: typeof MapaRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licencas': {
      id: '/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof LicencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ClientesRoute: ClientesRoute,
  LicencasRoute: LicencasRoute,
  MapaRoute: MapaRoute,
  MonitoramentoRoute: MonitoramentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
