/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegrasDiagnosticoRouteImport } from './routes/regras-diagnostico'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as MonitoramentoRouteImport } from './routes/monitoramento'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicencasRouteImport } from './routes/licencas'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FontesDadosRouteImport } from './routes/fontes-dados'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegrasDiagnosticoRoute = RegrasDiagnosticoRouteImport.update({
  id: '/regras-diagnostico',
  path: '/regras-diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoramentoRoute = MonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicencasRoute = LicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FontesDadosRoute = FontesDadosRouteImport.update({
  id: '/fontes-dados',
  path: '/fontes-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes-dados': typeof FontesDadosRoute
  '/historico': typeof HistoricoRoute
  '/landing': typeof LandingRoute
  '/licencas': typeof LicencasRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/membros': typeof MembrosRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/precos': typeof PrecosRoute
  '/regras-diagnostico': typeof RegrasDiagnosticoRoute
  '/signup': typeof SignupRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes-dados': typeof FontesDadosRoute
  '/historico': typeof HistoricoRoute
  '/landing': typeof LandingRoute
  '/licencas': typeof LicencasRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/membros': typeof MembrosRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/precos': typeof PrecosRoute
  '/regras-diagnostico': typeof RegrasDiagnosticoRoute
  '/signup': typeof SignupRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/fontes-dados': typeof FontesDadosRoute
  '/historico': typeof HistoricoRoute
  '/landing': typeof LandingRoute
  '/licencas': typeof LicencasRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/membros': typeof MembrosRoute
  '/monitoramento': typeof MonitoramentoRoute
  '/precos': typeof PrecosRoute
  '/regras-diagnostico': typeof RegrasDiagnosticoRoute
  '/signup': typeof SignupRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/clientes'
    | '/configuracoes'
    | '/fontes-dados'
    | '/historico'
    | '/landing'
    | '/licencas'
    | '/login'
    | '/mapa'
    | '/membros'
    | '/monitoramento'
    | '/precos'
    | '/regras-diagnostico'
    | '/signup'
    | '/accept-invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/clientes'
    | '/configuracoes'
    | '/fontes-dados'
    | '/historico'
    | '/landing'
    | '/licencas'
    | '/login'
    | '/mapa'
    | '/membros'
    | '/monitoramento'
    | '/precos'
    | '/regras-diagnostico'
    | '/signup'
    | '/accept-invite/$token'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/clientes'
    | '/configuracoes'
    | '/fontes-dados'
    | '/historico'
    | '/landing'
    | '/licencas'
    | '/login'
    | '/mapa'
    | '/membros'
    | '/monitoramento'
    | '/precos'
    | '/regras-diagnostico'
    | '/signup'
    | '/accept-invite/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FontesDadosRoute: typeof FontesDadosRoute
  HistoricoRoute: typeof HistoricoRoute
  LandingRoute: typeof LandingRoute
  LicencasRoute: typeof LicencasRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MembrosRoute: typeof MembrosRoute
  MonitoramentoRoute: typeof MonitoramentoRoute
  PrecosRoute: typeof PrecosRoute
  RegrasDiagnosticoRoute: typeof RegrasDiagnosticoRoute
  SignupRoute: typeof SignupRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regras-diagnostico': {
      id: '/regras-diagnostico'
      path: '/regras-diagnostico'
      fullPath: '/regras-diagnostico'
      preLoaderRoute: typeof RegrasDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoramento': {
      id: '/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof MonitoramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licencas': {
      id: '/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof LicencasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fontes-dados': {
      id: '/fontes-dados'
      path: '/fontes-dados'
      fullPath: '/fontes-dados'
      preLoaderRoute: typeof FontesDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FontesDadosRoute: FontesDadosRoute,
  HistoricoRoute: HistoricoRoute,
  LandingRoute: LandingRoute,
  LicencasRoute: LicencasRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MembrosRoute: MembrosRoute,
  MonitoramentoRoute: MonitoramentoRoute,
  PrecosRoute: PrecosRoute,
  RegrasDiagnosticoRoute: RegrasDiagnosticoRoute,
  SignupRoute: SignupRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
